# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: GroundMetadataTile.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from . import Shared_pb2 as Shared__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x18GroundMetadataTile.proto\x12\x0bstreetlevel\x1a\x0cShared.proto\"\xb3\x05\n\x12GroundMetadataTile\x12(\n\x04pano\x18\x01 \x03(\x0b\x32\x1a.streetlevel.PhotoPosition\x12\x44\n\nstorefront\x18\x03 \x03(\x0b\x32\x30.streetlevel.GroundMetadataTile.StorefrontBundle\x12\x31\n\x0b\x62uild_table\x18\x04 \x03(\x0b\x32\x1c.streetlevel.GroundDataBuild\x12\x34\n\x0f\x63\x61mera_metadata\x18\x05 \x03(\x0b\x32\x1b.streetlevel.CameraMetadata\x12\x34\n\x0ftile_coordinate\x18\x06 \x01(\x0b\x32\x1b.streetlevel.TileCoordinate\x1a\x97\x02\n\x10StorefrontBundle\x12\n\n\x02id\x18\x01 \x01(\x04\x12\x39\n\x0cpresentation\x18\x02 \x01(\x0b\x32#.streetlevel.StorefrontPresentation\x12M\n\x04\x66\x61\x63\x65\x18\x03 \x03(\x0b\x32?.streetlevel.GroundMetadataTile.StorefrontBundle.StorefrontFace\x12\x14\n\x0cmatched_muid\x18\x04 \x01(\x04\x1aW\n\x0eStorefrontFace\x12\x45\n\x08geometry\x18\x01 \x01(\x0b\x32\x33.streetlevel.GroundMetadataTile.OrientedBoundingBox\x1at\n\x13OrientedBoundingBox\x12/\n\x08position\x18\x01 \x01(\x0b\x32\x1d.streetlevel.OrientedPosition\x12\r\n\x05width\x18\x02 \x01(\x01\x12\x0e\n\x06height\x18\x03 \x01(\x01\x12\r\n\x05\x64\x65pth\x18\x04 \x01(\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'GroundMetadataTile_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _globals['_GROUNDMETADATATILE']._serialized_start=56
  _globals['_GROUNDMETADATATILE']._serialized_end=747
  _globals['_GROUNDMETADATATILE_STOREFRONTBUNDLE']._serialized_start=350
  _globals['_GROUNDMETADATATILE_STOREFRONTBUNDLE']._serialized_end=629
  _globals['_GROUNDMETADATATILE_STOREFRONTBUNDLE_STOREFRONTFACE']._serialized_start=542
  _globals['_GROUNDMETADATATILE_STOREFRONTBUNDLE_STOREFRONTFACE']._serialized_end=629
  _globals['_GROUNDMETADATATILE_ORIENTEDBOUNDINGBOX']._serialized_start=631
  _globals['_GROUNDMETADATATILE_ORIENTEDBOUNDINGBOX']._serialized_end=747
# @@protoc_insertion_point(module_scope)
