# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: Shared.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0cShared.proto\x12\x0bstreetlevel\"\"\n\x06LatLng\x12\x0b\n\x03lat\x18\x01 \x01(\x01\x12\x0b\n\x03lng\x18\x02 \x01(\x01*\xe1\x01\n\x0eMapsResultType\x12\x1c\n\x18MAPS_RESULT_TYPE_UNKNOWN\x10\x00\x12\x1a\n\x16MAPS_RESULT_TYPE_PLACE\x10\x01\x12\x1f\n\x1bMAPS_RESULT_TYPE_COLLECTION\x10\x02\x12\x1e\n\x1aMAPS_RESULT_TYPE_PUBLISHER\x10\x03\x12(\n$MAPS_RESULT_TYPE_PLACE_QUESTIONNAIRE\x10\x04\x12*\n&MAPS_RESULT_TYPE_BATCH_REVERSE_GEOCODE\x10\x05\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'Shared_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _globals['_MAPSRESULTTYPE']._serialized_start=66
  _globals['_MAPSRESULTTYPE']._serialized_end=291
  _globals['_LATLNG']._serialized_start=29
  _globals['_LATLNG']._serialized_end=63
# @@protoc_insertion_point(module_scope)
