# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: ResourceManifest.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x16ResourceManifest.proto\x12\x0bstreetlevel\"\xba\x03\n\x10ResourceManifest\x12?\n\x0cstyle_config\x18\x02 \x03(\x0b\x32).streetlevel.ResourceManifest.StyleConfig\x12\x10\n\x08token_p2\x18\x1e \x01(\t\x12\x16\n\x0e\x63\x61\x63he_base_url\x18\x1f \x01(\t\x12;\n\ncache_file\x18H \x03(\x0b\x32\'.streetlevel.ResourceManifest.CacheFile\x12\x14\n\x0c\x63\x61\x63he_file_2\x18\t \x03(\t\x1a\x1e\n\tCacheFile\x12\x11\n\tfile_name\x18\x02 \x01(\t\x1a\xc7\x01\n\x0bStyleConfig\x12\x14\n\x0curl_prefix_1\x18\x01 \x01(\t\x12\x14\n\x0curl_prefix_2\x18\t \x01(\t\x12\x43\n\x08style_id\x18\x03 \x01(\x0e\x32\x31.streetlevel.ResourceManifest.StyleConfig.StyleID\"G\n\x07StyleID\x12\x05\n\x01_\x10\x00\x12\n\n\x06\x43\x33MM_1\x10\x0e\x12\x07\n\x03\x43\x33M\x10\x0f\x12\t\n\x05\x44TM_1\x10\x10\x12\t\n\x05\x44TM_2\x10\x11\x12\n\n\x06\x43\x33MM_2\x10\x34\x62\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'ResourceManifest_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _RESOURCEMANIFEST._serialized_start=40
  _RESOURCEMANIFEST._serialized_end=482
  _RESOURCEMANIFEST_CACHEFILE._serialized_start=250
  _RESOURCEMANIFEST_CACHEFILE._serialized_end=280
  _RESOURCEMANIFEST_STYLECONFIG._serialized_start=283
  _RESOURCEMANIFEST_STYLECONFIG._serialized_end=482
  _RESOURCEMANIFEST_STYLECONFIG_STYLEID._serialized_start=411
  _RESOURCEMANIFEST_STYLECONFIG_STYLEID._serialized_end=482
# @@protoc_insertion_point(module_scope)
